<?php

namespace System\Helpers\Classes\HtmlCleaner;

/**
 * Class Builder
 * @package System\Helpers\Classes\HtmlCleaner
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_a a($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_abbr abbr($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_acronym acronym($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_address address($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_applet applet($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_area area($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_article article($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_aside aside($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_audio audio($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_b b($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_base base($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_basefont basefont($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_bdi bdi($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_bdo bdo($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_big big($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_blockquote blockquote($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_body body($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_br br($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_button button($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_canvas canvas($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_caption caption($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_center center($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_cite cite($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_code code($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_col col($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_colgroup colgroup($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_data data($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_datalist datalist($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_dd dd($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_del del($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_details details($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_dfn dfn($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_dialog dialog($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_dir dir($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_div div($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_dl dl($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_dt dt($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_em em($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_embed embed($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_fieldset fieldset($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_figcaption figcaption($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_figure figure($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_font font($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_footer footer($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_form form($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_frame frame($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_frameset frameset($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_h1 h1($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_h2 h2($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_h3 h3($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_h4 h4($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_h5 h5($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_h6 h6($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_head head($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_header header($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_hgroup hgroup($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_hr hr($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_html html($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_i i($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_iframe iframe($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_img img($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_input input($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_ins ins($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_kbd kbd($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_label label($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_legend legend($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_li li($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_link link($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_main main($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_map map($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_mark mark($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_menu menu($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_meta meta($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_meter meter($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_nav nav($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_noframes noframes($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_noscript noscript($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_object object($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_ol ol($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_optgroup optgroup($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_option option($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_output output($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_p p($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_param param($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_picture picture($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_pre pre($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_progress progress($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_q q($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_rp rp($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_rt rt($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_ruby ruby($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_s s($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_samp samp($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_script script($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_search search($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_section section($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_select select($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_small small($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_source source($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_span span($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_strike strike($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_strong strong($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_style style($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_sub sub($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_summary summary($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_sup sup($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_svg svg($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_table table($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_tbody tbody($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_td td($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_template template($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_textarea textarea($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_tfoot tfoot($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_th th($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_thead thead($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_time time($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_title title($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_tr tr($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_track track($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_tt tt($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_u u($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_ul ul($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_var var($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_video video($removeTagWithoutAttributes = false)
 * @method \System\Helpers\Classes\HtmlCleaner\Tags\Tag_wbr wbr($removeTagWithoutAttributes = false)

 */
class Builder
{
    protected $tags = array();

    public function __call($name, $arguments)
    {
        return $this->tag($name, ...$arguments);
    }

    public function __construct(&$tags)
    {
        $this->tags = &$tags;
    }

    public function tag($tag, $removeTagWithoutAttributes = false)
    {
        $attributes = new Attributes($tag, $this->tags);
        $attributes->option('removeTagWithoutAttributes', $removeTagWithoutAttributes);
        return $attributes;
    }
}