<?php

namespace System\Core\Database\Statics;

class TableOptions
{
    const MYSQL_COMPRESSION_Z_LIB = "ZLIB";
    const MYSQL_COMPRESSION_LZ4 = "LZ4";
    const MYSQL_COMPRESSION_NONE = "NONE";

    const MYSQL_ENCRYPTION_YES = "Y";
    const MYSQL_ENCRYPTION_NO = "N";

    const MYSQL_ENGINE_INNO_DB = "InnoDB";
    const MYSQL_ENGINE_MY_ISAM = "MyISAM";

    const MYSQL_INSERT_METHOD_NO = "NO";
    const MYSQL_INSERT_METHOD_FIRST = "FIRST";
    const MYSQL_INSERT_METHOD_LAST = "LAST";

    const MYSQL_PACK_KEYS_TRUE = "1";
    const MYSQL_PACK_KEYS_FALSE = "0";
    const MYSQL_PACK_KEYS_DEFAULT = "DEFAULT";

    const MYSQL_ROW_FORMAT_DEFAULT = "DEFAULT";
    const MYSQL_ROW_FORMAT_DYNAMIC = "DYNAMIC";
    const MYSQL_ROW_FORMAT_FIXED = "FIXED";

    const MYSQL_ROW_FORMAT_COMPRESSED = "COMPRESSED";
    const MYSQL_ROW_FORMAT_REDUNDANT = "REDUNDANT";
    const MYSQL_ROW_FORMAT_COMPACT = "COMPACT";

    const MYSQL_STATS_AUTO_RE_CALC_TRUE = "1";
    const MYSQL_STATS_AUTO_RE_CALC_FALSE = "0";
    const MYSQL_STATS_AUTO_RE_CALC_DEFAULT = "DEFAULT";

    const MYSQL_STATS_PERSISTENT_TRUE = "1";
    const MYSQL_STATS_PERSISTENT_FALSE = "0";
    const MYSQL_STATS_PERSISTENT_DEFAULT = "DEFAULT";
}